apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rideshare-matching-service-secrets
spec:
  secretStoreRef:
    name: aws-secrets-manager
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: rideshare/staging/matching-service
        property: DATABASE_URL
    - secretKey: JWT_SECRET
      remoteRef:
        key: rideshare/staging/matching-service
        property: JWT_SECRET
    - secretKey: REDIS_URL
      remoteRef:
        key: rideshare/staging/matching-service
        property: REDIS_URL
