apiVersion: v1
kind: ConfigMap
metadata:
  name: rideshare-frontend-config
data:
  NEXT_PUBLIC_RIDER_SERVICE_URL: "http://rideshare-rider-service.rideshare-dev-chris.svc.cluster.local"
  NEXT_PUBLIC_DRIVER_SERVICE_URL: "http://rideshare-driver-service.rideshare-dev-chris.svc.cluster.local"
  NEXT_PUBLIC_TRIP_SERVICE_URL: "http://rideshare-trip-service.rideshare-dev-chris.svc.cluster.local"
  NEXT_PUBLIC_WS_URL: "ws://rideshare-trip-service.rideshare-dev-chris.svc.cluster.local"
  NEXT_PUBLIC_TRIP_WS_URL: "ws://rideshare-trip-service.rideshare-dev-chris.svc.cluster.local"
