apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rideshare-frontend-secrets
  labels:
    app: rideshare-frontend
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: PLACEHOLDER_SECRET_STORE
    kind: ClusterSecretStore
  target:
    name: rideshare-frontend-secrets
    creationPolicy: Owner
  data:
    - secretKey: NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN
      remoteRef:
        key: PLACEHOLDER_AWS_SECRET_NAME
        property: NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN
