apiVersion: v1
kind: Service
metadata:
  name: rideshare-frontend
  labels:
    app: rideshare-frontend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: rideshare-frontend
