apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rideshare-frontend-secrets
spec:
  secretStoreRef:
    name: aws-secretsmanager-staging
  data:
    - secretKey: NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN
      remoteRef:
        key: rideshare/staging/frontend
        property: NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN
